# Permalinks

permalinks: pretty

# Setup
title: Yrsa – open-source fonts for Latin + Gujarati
description: Yrsa – open-source fonts for Latin + Gujarati by Rosetta
baseurl: "/yrsa/"

# About/contact
author:
  name: Rosetta
  url: https://rosettatype.com
  email: info@rosettatype.com

# Build settings
markdown: kramdown

# Articles showed on homepage
include: ['_pages']
articles:
  - title: Introducing Yrsa
    link: introducing-yrsa/
    description: First intro to the project and some thinking behind/about it
  - title: Language support
    link: language-support/
    description: Intended language support in Latin and Gujarati scripts
  - title: What is Rosetta
    link: http://github.rosettatype.com
    description: Learn about Rosetta and its open-source projects

